Homework 5
VikaOnoshko/course pull request #3
Opened 2023-02-05 19:17 UTC by VikaOnoshko

2023-02-06 09:27 UTC, UladTeachMeSkills requested changes

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/css/banner.css
> +  width: 1170px;
Фиксированная ширина :(

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/css/banner.css
> +  font-family: "Open Sans";
Выбери один общий шрифт и занеси его в body, перепроверь все свои переопределения шрифтов и удали лишние

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/css/contact.css
> +  width: 1170px;
Не надо так :(

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/css/contact.css
> +  margin: 0 -15px;
Отрицательный margin? Точно есть необходимость?

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/css/footer.css
> +  font-family: "Raleway";
Боль :(

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/css/reviews.css
> +  width: 1170px;
👎

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/css/reviews.css
> +  font-family: "Raleway";
same

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/css/reviews.css
> +  font-family: "Raleway";
same

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/index.html
> +    <link rel="stylesheet" href="./css/reviews.css"/>
Обрати внимание на файловую структуру, которую я сбросил в телегу и занеси все файлы css в один файл index.css при помощи @import. Далее подключи тот единственный файл index.css в index.html

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/index.html
> +                src="./assets/img/Ellipse 7.png"
Пробелы в имени файлов

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/index.html
> +                src="./assets/img/ava 3.png"
same

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/index.html
> +            <button class="design__button">Download</button>
type button

2023-02-06 09:27 UTC, UladTeachMeSkills commented on axit-project-Onoshko/index.html
> +          </div>
Вот это всё должно лежать в теге form.
contact__button возможно имеет другой текст
contact__button должна содержать type submit

2023-02-06 18:26 UTC, VikaOnoshko commented on axit-project-Onoshko/css/contact.css
> +  margin: 0 -15px;
это с делала по видосу который ты рекомендовал посмотреть ,в видосе сказали ,что это крутой споооб, так я так и сделала)))

2023-02-06 21:51 UTC, VikaOnoshko commented on axit-project-Onoshko/css/contact.css
> +  margin: 0 -15px;
а как можно было сделать?

2023-02-06 21:52 UTC, VikaOnoshko commented on axit-project-Onoshko/css/contact.css
> +  margin: 0 -15px;
Я смотрела видео, которое ты скинул по флексам и там использовали в одном месте такой способ и сказали,что он хороший.

2023-02-08 18:28 UTC, UladTeachMeSkills approved these changes

2023-02-08 18:58 UTC, merged